import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Old_Standard_TT } from "next/font/google";
import { twMerge } from "tailwind-merge";
import Header from "@/components/Header";
const old_standard = Old_Standard_TT({ weight: "400", subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge(old_standard.className, "bg-stella p-12")}>
        <Header />
        {children}
      </body>
    </html>
  );
}
